function [BW,maskedRGBImage] = CreateMaskImg(RGB, colorSpace, channel1, channel2, channel3)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 09-Feb-2024
%------------------------------------------------------

% Convert RGB image to chosen color space
    switch colorSpace
        case 'RGB'
            I = RGB;
            channel1Min = 255.0 * channel1(1);
            channel1Max = 255.0 * channel1(2);
            channel2Min = 255.0 * channel2(1);
            channel2Max = 255.0 * channel2(2);
            channel3Min = 255.0 * channel3(1);
            channel3Max = 255.0 * channel3(2);
        case 'HSV'
            I = rgb2hsv(RGB);
            channel1Min = channel1(1);
            channel1Max = channel1(2);
            channel2Min = channel2(1);
            channel2Max = channel2(2);
            channel3Min = channel3(1);
            channel3Max = channel3(2);
        case 'YCbCr'
            I = rgb2ycbcr(RGB);
            channel1Min = 255.0 * channel1(1);
            channel1Max = 255.0 * channel1(2);
            channel2Min = 255.0 * channel2(1);
            channel2Max = 255.0 * channel2(2);
            channel3Min = 255.0 * channel3(1);
            channel3Max = 255.0 * channel3(2);
        case 'L*a*b*'
            I = rgb2lab(RGB);
            channel1Min = 100.0 * channel1(1);
            channel1Max = 100.0 * channel1(2);
            channel2Min = (200.0 * channel2(1)) - 100.0;
            channel2Max = (200.0 * channel2(2)) - 100.0;
            channel3Min = (200.0 * channel3(1)) - 100.0;
            channel3Max = (200.0 * channel3(2)) - 100.0;
    end
    
    % Create mask based on chosen histogram thresholds
    sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
        (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
        (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
    BW = sliderBW;
    
    % Initialize output masked image based on input image.
    maskedRGBImage = RGB;
    
    % Set background pixels where BW is false to zero.
    maskedRGBImage(repmat(~BW,[1 1 3])) = 0;
end